import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

  const faviconDataUri =`<svg width="100" height="100" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
      <path d="M50 0 L25 85 L50 70 L75 85 Z" fill="#FF5722"/>
      <polygon points="50,0 45,70 55,70" fill="#E64A19"/>
      <polygon points="25,85 50,70 75,85" fill="#BF360C"/>
      <circle cx="50" cy="50" r="10" fill="#FFC107"/>
      <path d="M50 0 L50 70 L75 85 L50 0 Z" fill="rgba(0,0,0,0.1)"/>
    </svg>`;

export const metadata: Metadata = {
  title: "Rss Feeder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <head>
        <link rel="icon" href={faviconDataUri} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
